services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=XXXXX
      - POSTGRES_USER=XXXXX
      - POSTGRES_DB=XXXXX
    networks:
      p_vpc:
        ipv4_address: 10.5.0.5

networks:
  p_vpc:
    name: commonNetwork
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1